back end deployment

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,6 +15,29 @@ commands:
             aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
             aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
           when: << parameters.when_to_run >>
+
+
+
+  revert-migrations:
+    description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
+    steps:
+      - run:
+          name: Revert migrations
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS = 1
+            if(( $SUCCESS==1 )); 
+            then
+            #  cd ~/project/backend
+            #  npm install
+            #  Add revert code here. You can find this in the Getting Started section.
+              exit 1
+            fi
+
+
 jobs:
   build-frontend:
     docker:
@@ -142,11 +165,11 @@ jobs:
             --region us-east-1 \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --output text >> .circleci/ansible/inventory.txt
+            --output text >> ~/project/.circleci/ansible/inventory.txt
       - persist_to_workspace:
-          root: .
+          root: ~/
           paths:
-            - .circleci/ansible/*
+            - project/.circleci/ansible/*
       - destroy-environment
 
   
@@ -169,7 +192,7 @@ jobs:
             apk add --update --no-cache tar gzip ansible aws-cli
       # attach workspace
       - attach_workspace:
-          at: .
+          at: ~/
       - run:
           name: Configure server
           command: |
@@ -178,8 +201,118 @@ jobs:
             --key-file ~/.ssh/id_rsa_7d27a10f082d138b202853862b1d4bc8
       # Here's where you will add some code to rollback on failure
       - destroy-environment
-          
-            
+
+  
+  run-migrations:
+    docker:
+      - image: circleci/node
+    steps:
+      - checkout
+      - run: 
+          name: install dependencies
+          command: |
+            apk add --update --no-cache tar gzip aws-cli curl
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Run migrations
+          command: |
+            cd backend
+            npm install
+            npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+           # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+              curl https://kvdb.io/THhJR6187AUXkZqje3mh8T/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
+            fi
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+
+
+  deploy-frontend:
+    docker:
+      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            yum update -y
+            yum upgrade -y
+            yum install -ya curl 
+            yum install -y tar gzip
+            yum install python3.9 -y
+            update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
+            yum install awscli -y
+            yum install -y gcc-c++ make 
+            curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash - 
+            yum install -y nodejs 
+            apk add --update --no-cache  nodejs npm aws-cli python curl
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --region us-east-1 \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}")
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+        # Here's where you will add some code to rollback on failure           
+      - destroy-environment
+
+
+  deploy-backend:
+    docker:
+      # Docker image here that supports Ansible
+      - image: python:3.10-alpine3.16
+      # - image: amazon/aws-cli
+    steps:
+      # Checkout code from git
+      - checkout
+      - run: apk add --update openssh-client git
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints:
+            - '7d:27:a1:0f:08:2d:13:8b:20:28:53:86:2b:1d:4b:c8'
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache tar gzip ansible aws-cli
+      - run:
+          name: Deploy backend
+          command: |
+            cd backend
+            npm i
+            npm run build
+            cd ..
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+            cd .circleci/ansible
+            echo "Contents  of the inventory.txt file is -------"
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+            --key-file ~/.ssh/id_rsa_7d27a10f082d138b202853862b1d4bc8
+      # Here's where you will add some code to rollback on failure    
+      - destroy-environment    
           
           
  
@@ -200,12 +333,12 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-    #- run-migrations:
-    #    requires: [configure-infrastructure]
-    #- deploy-frontend:
-    #    requires: [run-migrations]
-    #- deploy-backend:
-    #    requires: [run-migrations]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend:
+          requires: [run-migrations]
     #- smoke-test:
     #    requires: [deploy-backend, deploy-frontend]
     #- cloudfront-update:
